package org.jengine.in;
// Generated Aug 20, 2006 6:44:10 PM by Hibernate Tools 3.2.0.beta6a


import java.util.Date;

/**
 * Main generated by hbm2java
 */
public class Main  implements java.io.Serializable {

    // Fields    

     private String testId;
     private String result;
     private Integer ctrl;
     private String cmt;
     private Date runDate;
     private String patId;
     private String name;
     private String sex;
     private Date dob;
     private String lo;
     private String hi;
     private String ref;
     private String accno;
     private Date drawDaTi;
     private String tech;
     private String collector;
     private String drName;
     private String testName;
     private Integer row;
     private String astm;
     private Integer age;
     private Date recDt;
     //private Date postDt;
     private String postDt;
     private String acceptor;
     private Integer printCt;
     private String cmtNotify;
     private String unit;
     private String profile;
     private String analyzer;
     private String sampleType;
     private String room;
     private String stat;
     private Integer offs;
     private String location;
     //private DrName ordPhys;
     private String ordPhys;
     private String sampleCmt;
     private Integer faxCt;
     private Integer xmitCt;
     private Date print1st;
     private Date fax1st;
     private Date xmit1st;
     private Date printLast;
     private Date faxLast;
     private Date xmitLast;
     private String account;
     private String editId;
     private Date editDt;
     private Integer delta;
     private String newAge;
     private String cpt;
     private String receiver;
     private String rbocode;
     private String dist1;
     private String dist2;
     private String dist3;
     private String dist4;
     private String dist5;
     private String labCmt;

     // Constructors

    /** default constructor */
    public Main() {
    }

	/** minimal constructor */
    public Main(String testId) {
        this.testId = testId;
    }
    public String getTestId() { return testId; }
    public void setTestId(String id) { this.testId = id; }

    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public Integer getCtrl() {
        return this.ctrl;
    }
    
    public void setCtrl(Integer ctrl) {
        this.ctrl = ctrl;
    }
    public String getCmt() {
        return this.cmt;
    }
    
    public void setCmt(String cmt) {
        this.cmt = cmt;
    }
    public Date getRunDate() {
        return this.runDate;
    }
    
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }
    public String getPatId() {
        return this.patId;
    }
    
    public void setPatId(String patId) {
        this.patId = patId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getLo() {
        return this.lo;
    }
    
    public void setLo(String lo) {
        this.lo = lo;
    }
    public String getHi() {
        return this.hi;
    }
    
    public void setHi(String hi) {
        this.hi = hi;
    }
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }
    public String getAccno() {
        return this.accno;
    }
    
    public void setAccno(String accno) {
        this.accno = accno;
    }
    public Date getDrawDaTi() {
        return this.drawDaTi;
    }
    
    public void setDrawDaTi(Date drawDaTi) {
        this.drawDaTi = drawDaTi;
    }
    public String getTech() {
        return this.tech;
    }
    
    public void setTech(String tech) {
        this.tech = tech;
    }
    public String getCollector() {
        return this.collector;
    }
    
    public void setCollector(String collector) {
        this.collector = collector;
    }
    public String getDrName() {
        return this.drName;
    }
    
    public void setDrName(String drName) {
        this.drName = drName;
    }
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }
    public Integer getRow() {
        return this.row;
    }
    
    public void setRow(Integer row) {
        this.row = row;
    }
    public String getAstm() {
        return this.astm;
    }
    
    public void setAstm(String astm) {
        this.astm = astm;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Date getRecDt() {
        return this.recDt;
    }
    
    public void setRecDt(Date recDt) {
        this.recDt = recDt;
    }
    public String getPostDt() {
        return this.postDt;
    }
    
    public void setPostDt(String postDt) {
        this.postDt = postDt;
    }
    public String getAcceptor() {
        return this.acceptor;
    }
    
    public void setAcceptor(String acceptor) {
        this.acceptor = acceptor;
    }
    public Integer getPrintCt() {
        return this.printCt;
    }
    
    public void setPrintCt(Integer printCt) {
        this.printCt = printCt;
    }
    public String getCmtNotify() {
        return this.cmtNotify;
    }
    
    public void setCmtNotify(String cmtNotify) {
        this.cmtNotify = cmtNotify;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }
    public String getAnalyzer() {
        return this.analyzer;
    }
    
    public void setAnalyzer(String analyzer) {
        this.analyzer = analyzer;
    }
    public String getSampleType() {
        return this.sampleType;
    }
    
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }
    public Integer getOffs() {
        return this.offs;
    }
    
    public void setOffs(Integer offs) {
        this.offs = offs;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
/*
    public DrName getOrdPhys() {
        return this.ordPhys;
    }
*/
    public String getOrdPhys() {
        return this.ordPhys;
    }
    
/*
    public void setOrdPhys(DrName ordPhys) {
        this.ordPhys = ordPhys;
    }
*/
    public void setOrdPhys(String ordPhys) {
        this.ordPhys = ordPhys;
    }
    public String getSampleCmt() {
        return this.sampleCmt;
    }
    
    public void setSampleCmt(String sampleCmt) {
        this.sampleCmt = sampleCmt;
    }
    public Integer getFaxCt() {
        return this.faxCt;
    }
    
    public void setFaxCt(Integer faxCt) {
        this.faxCt = faxCt;
    }
    public Integer getXmitCt() {
        return this.xmitCt;
    }
    
    public void setXmitCt(Integer xmitCt) {
        this.xmitCt = xmitCt;
    }
    public Date getPrint1st() {
        return this.print1st;
    }
    
    public void setPrint1st(Date print1st) {
        this.print1st = print1st;
    }
    public Date getFax1st() {
        return this.fax1st;
    }
    
    public void setFax1st(Date fax1st) {
        this.fax1st = fax1st;
    }
    public Date getXmit1st() {
        return this.xmit1st;
    }
    
    public void setXmit1st(Date xmit1st) {
        this.xmit1st = xmit1st;
    }
    public Date getPrintLast() {
        return this.printLast;
    }
    
    public void setPrintLast(Date printLast) {
        this.printLast = printLast;
    }
    public Date getFaxLast() {
        return this.faxLast;
    }
    
    public void setFaxLast(Date faxLast) {
        this.faxLast = faxLast;
    }
    public Date getXmitLast() {
        return this.xmitLast;
    }
    
    public void setXmitLast(Date xmitLast) {
        this.xmitLast = xmitLast;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getEditId() {
        return this.editId;
    }
    
    public void setEditId(String editId) {
        this.editId = editId;
    }
    public Date getEditDt() {
        return this.editDt;
    }
    
    public void setEditDt(Date editDt) {
        this.editDt = editDt;
    }
    public Integer getDelta() {
        return this.delta;
    }
    
    public void setDelta(Integer delta) {
        this.delta = delta;
    }
    public String getNewAge() {
        return this.newAge;
    }
    
    public void setNewAge(String newAge) {
        this.newAge = newAge;
    }
    public String getCpt() {
        return this.cpt;
    }
    
    public void setCpt(String cpt) {
        this.cpt = cpt;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public String getRbocode() {
        return this.rbocode;
    }
    
    public void setRbocode(String rbocode) {
        this.rbocode = rbocode;
    }
    public String getDist1() {
        return this.dist1;
    }
    
    public void setDist1(String dist1) {
        this.dist1 = dist1;
    }
    public String getDist2() {
        return this.dist2;
    }
    
    public void setDist2(String dist2) {
        this.dist2 = dist2;
    }
    public String getDist3() {
        return this.dist3;
    }
    
    public void setDist3(String dist3) {
        this.dist3 = dist3;
    }
    public String getDist4() {
        return this.dist4;
    }
    
    public void setDist4(String dist4) {
        this.dist4 = dist4;
    }
    public String getDist5() {
        return this.dist5;
    }
    
    public void setDist5(String dist5) {
        this.dist5 = dist5;
    }
    public String getLabCmt() {
        return this.labCmt;
    }
    
    public void setLabCmt(String labCmt) {
        this.labCmt = labCmt;
    }


    public String toString() {
	java.lang.StringBuffer sb = new java.lang.StringBuffer();

	sb.append("Main ::: getAcceptor()=" + getAcceptor());
	sb.append(",getAccno()=" + getAccno());
	sb.append(",getAccount()=" + getAccount());
	sb.append(",getAge()=" + getAge());
	sb.append(",getAnalyzer()=" + getAnalyzer());
	sb.append(",getAstm()=" + getAstm());
	sb.append(",getCmt()=" + getCmt());
	sb.append(",getCmtNotify()=" + getCmtNotify());
	sb.append(",getCollector()=" + getCollector());
	sb.append(",getCpt()=" + getCpt());
	sb.append(",getCtrl()=" + getCtrl());
	sb.append(",getDelta()=" + getDelta());
	sb.append(",getDist1()=" + getDist1());
	sb.append(",getDist2()=" + getDist2());
	sb.append(",getDist3()=" + getDist3());
	sb.append(",getDist4()=" + getDist4());
	sb.append(",getDist5()=" + getDist5());
	sb.append(",getDob()=" + getDob());
	sb.append(",getDrName()=" + getDrName());
	sb.append(",getDrawDaTi()=" + getDrawDaTi());
	sb.append(",getEditDt()=" + getEditDt());
	sb.append(",getEditId()=" + getEditId());
	sb.append(",getFax1st()=" + getFax1st());
	sb.append(",getFaxCt()=" + getFaxCt());
	sb.append(",getFaxLast()=" + getFaxLast());
	sb.append(",getHi()=" + getHi());
	sb.append(",getLabCmt()=" + getLabCmt());
	sb.append(",getLo()=" + getLo());
	sb.append(",getLocation()=" + getLocation());
	sb.append(",getName()=" + getName());
	sb.append(",getNewAge()=" + getNewAge());
	sb.append(",getOffs()=" + getOffs());
	sb.append(",getOrdPhys()=" + getOrdPhys());
	sb.append(",getPatId()=" + getPatId());
	sb.append(",getPostDt()=" + getPostDt());
	sb.append(",getPrint1st()=" + getPrint1st());
	sb.append(",getPrintCt()=" + getPrintCt());
	sb.append(",getPrintLast()=" + getPrintLast());
	sb.append(",getProfile()=" + getProfile());
	sb.append(",getRbocode()=" + getRbocode());
	sb.append(",getRecDt()=" + getRecDt());
	sb.append(",getReceiver()=" + getReceiver());
	sb.append(",getRef()=" + getRef());
	sb.append(",getResult()=" + getResult());
	sb.append(",getRoom()=" + getRoom());
	sb.append(",getRow()=" + getRow());
	sb.append(",getRunDate()=" + getRunDate());
	sb.append(",getSampleCmt()=" + getSampleCmt());
	sb.append(",getSampleType()=" + getSampleType());
	sb.append(",getSex()=" + getSex());
	sb.append(",getStat()=" + getStat());
	sb.append(",getTech()=" + getTech());
	sb.append(",getTestId()=" + getTestId());
	sb.append(",getTestName()=" + getTestName());
	sb.append(",getUnit()=" + getUnit());
	sb.append(",getXmit1st()=" + getXmit1st());
	sb.append(",getXmitCt()=" + getXmitCt());
	sb.append(",getXmitLast()=" + getXmitLast());

	return sb.toString();
     }


}


